### ISSUE TITLE
NAD27 to WGS84/NAD83 does not calculate correctly

### ISSUE THREAD

**Issue by caleb87** [proj4js/proj4js#212] opened 2016-10-05 22:52 UTC
The following code does not convert NAD27 coordinates to NAD83 correctly. Am I doing something wrong?

```
<script src="proj4js/dist/proj4.js"></script>
<script>
var nad27 = '+proj=longlat +ellps=clrk66 +datum=NAD27 +no_defs';
var nad83 = "+proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs";    
var a = proj4(nad27,nad83,[-110.045977,33.081801]); // 33.081801,-110.045977
console.log(a[1]+','+a[0]); // 33.079841471460625,-110.04597700000001
// correct coordinate: 33.0818596,-110.0466177
</script>
```

**Comment by calvinmetcalf** [comment] 2016-10-06 00:03
Correct according to whom?

**Comment by caleb87** [comment] 2016-10-06 00:47
Hi calvin,

Both QGIS and http://www.apsalin.com/nad-conversion.aspx created correct coordinate version and as well as my personal knowledge of the relation of NAD27/NAD83. Typically in any region in the United States NAD83 will not convert drastically south of the NAD27 point. I also compared points according to government agencies. Its definitely wrong.

**Comment by caleb87** [comment] 2016-10-06 01:09
QGIS Conversion from NAD27 to NAD83 is 33.0818596090588,-110.046617714068

apsalin.com is: 33.081801,-110.045977

proj4js and proj4php are both: 33.079841471460625,-110.04597700000001

**Comment by calvinmetcalf** [comment] 2016-10-06 01:23
Ok great that's exactly what I was looking for, I'll take a look when I have some time.

**Comment by mbloch** [comment] 2016-10-06 07:55
Could be the problem is that proj4js does not support grid transformations, so it is unable to correctly convert from NAD27.

**Comment by calvinmetcalf** [comment] 2016-10-06 14:18
right that would do it

**Comment by caleb87** [comment] 2016-10-06 15:00
Any idea how to do the grid transformation in JS or PHP?

**Comment by calvinmetcalf** [comment] 2016-10-06 15:42
depends if you can call out to c (because your running this in php or in node) then just call out to the regular proj4

**Comment by caleb87** [comment] 2016-10-06 17:27
I installed proj4 and tried it which worked. This works for me, though I am still going to try to get a PHP/JS function to convert NAD27 to NAD83 even if it's not as accurate as proj4. If I do find it, I'll post it in this thread. That way one library can be used.

The command for proj4 to convert from NAD27 to NAD83 is below:

```
cs2cs +proj=latlong +ellps=clrk66 +nadgrids=conus,null \
    +to +proj=latlong +ellps=GRS80 +datum=NAD83 << EOF
 -110.045977 33.081801
EOF
```
OUTPUT:
110d2'47.824"W  33d4'54.695"N 0.000

**Comment by calvinmetcalf** [comment] 2017-05-18 14:07
yeah we're not going to be supporting grids anytime soon sorry closing

**Closed by calvinmetcalf** 2017-05-18 14:07 UTC
